name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ matrix.os }}-${{ matrix.node-version }}-build-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ matrix.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
      #       ${{ matrix.os }}-${{ matrix.node-version }}-build-
      #       ${{ matrix.os }}-${{ matrix.node-version }}-
      # - name: Cache Cypress
      #   uses: actions/cache@v1
      #   with:
      #     path: /home/runner/.cache/Cypress
      #     key: ${{ matrix.os }}-${{ matrix.node-version }}-cypress-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ matrix.os }}-${{ matrix.node-version }}-cypress-${{ env.cache-name }}-
      #       ${{ matrix.os }}-${{ matrix.node-version }}-cypress-
      #       ${{ matrix.os }}-${{ matrix.node-version }}-
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Build docs
        run: npm run docs
      - name: Deploy docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
      - name: check formatting
        if: always()
        run: npm run format:check
        env:
          CI: true
          NODE_ENV: test
      - name: lint
        if: always()
        run: npm run lint
        env:
          CI: true
